### ISSUE TITLE
diamond operator check gives false positive

### ISSUE THREAD

**Issue by yegor256** [yegor256/qulice#1242]
This is the code:

```
import java.util.Map;
import org.cactoos.map.MapEntry;
import org.cactoos.map.MapOf;

void foo() {
  Map<String, String> params = new MapOf<String, String>(
    new MapEntry<>("a", "foo"),
    new MapEntry<>("b", "foo")
  );
}
```

Qulice complains with `PMD.UseDiamondOperator` and `DiamondOperatorCheck`. However, I can't turn `MapOf<String, String>` into `MapOf<>`, because it won't compile. Can we do something about this?

**Comment by yegor256** [comment]
@pnatashap can you try to help?

**Comment by pnatashap** [comment]
@yegor256 looks like this issue is solved in PMD 7 (they move rule to java code from XSL) https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UseDiamondOperatorRule.java 
not sure that it is enough functionality in version 6 to just copy it, they have really change a lot. Will check migration guide.
